<?php

$sLangName = 'Deutsch';

$aLang = [
    'charset' => 'UTF-8',

    'SHOP_MODULE_GROUP_unzer_payment_main' => 'Basis Settings',
    'SHOP_MODULE_GROUP_unzer_payment_specific' => 'Erweiterte Einstellungen',
    'SHOP_MODULE_UnzerPaymentMode' => 'Modus',
    'SHOP_MODULE_UnzerPaymentMode_0' => 'Sandbox',
    'SHOP_MODULE_UnzerPaymentMode_1' => 'Production',
    'SHOP_MODULE_UnzerPaymentPublicKey' => 'Public Key',
    'SHOP_MODULE_UnzerPaymentPrivateKey' => 'Private Key',
    'SHOP_MODULE_UnzerPaymentLogLevel' => 'Log Level',
    'SHOP_MODULE_UnzerPaymentLogLevel_ERROR' => 'ERROR: Nur Fehlermeldungen loggen',
    'SHOP_MODULE_UnzerPaymentLogLevel_WARNING' => 'WARNING: Warnungen und Fehlermeldungen loggen',
    'SHOP_MODULE_UnzerPaymentLogLevel_DEBUG' => 'DEBUG: Alle Informationen loggen',
    'SHOP_MODULE_UnzerPaymentClickToPay' => 'Click to Pay für Kreditkartenzahlungen aktivieren',
    'SHOP_MODULE_UnzerPaymentCardChargeMode' => 'Kreditkarte Buchungsmodus',
    'SHOP_MODULE_UnzerPaymentApplepayChargeMode' => 'Apple Pay Buchungsmodus',
    'SHOP_MODULE_UnzerPaymentGooglepayChargeMode' => 'Google Pay Buchungsmodus',
    'SHOP_MODULE_UnzerPaymentPaypalChargeMode' => 'Paypal Buchungsmodus',
    'SHOP_MODULE_UnzerPaymentWeroChargeMode' => 'Wero Buchungsmodus',
    'SHOP_MODULE_UnzerPaymentCardChargeMode_authorize' => 'Autorisierung',
    'SHOP_MODULE_UnzerPaymentCardChargeMode_charge' => 'Einzug',
    'SHOP_MODULE_UnzerPaymentApplepayChargeMode_authorize' => 'Autorisierung',
    'SHOP_MODULE_UnzerPaymentApplepayChargeMode_charge' => 'Einzug',
    'SHOP_MODULE_UnzerPaymentGooglepayChargeMode_authorize' => 'Autorisierung',
    'SHOP_MODULE_UnzerPaymentGooglepayChargeMode_charge' => 'Einzug',
    'SHOP_MODULE_UnzerPaymentPaypalChargeMode_authorize' => 'Autorisierung',
    'SHOP_MODULE_UnzerPaymentPaypalChargeMode_charge' => 'Einzug',
    'SHOP_MODULE_UnzerPaymentWeroChargeMode_authorize' => 'Autorisierung',
    'SHOP_MODULE_UnzerPaymentWeroChargeMode_charge' => 'Einzug',
    'UNZER_WEBHOOKS' => 'Webhooks',
    'UNZER_ID' => 'ID',
    'UNZER_ORDERNR' => 'Unzer OrderNr.',
    'UNZER_SHORT_ID' => 'Short-ID',
    'UNZER_WEBHOOK_EVENT' => 'Event',
    'UNZER_WEBHOOK_URL' => 'URL',
    'UNZER_WEBHOOK_DELETE_CONFIRM' => 'Möchten Sie den Webhook wirklich löschen?',
    'UNZER_WEBHOOK_CREATE_CONFIRM' => 'Möchten Sie den Webhook wirklich registrieren?',
    'UNZER_CREATE_WEBHOOK' => 'Webhook registrieren',
    'tbclorder_unzerpayment' => 'Unzer Payment',
    'NO_UNZER_PAYMENT_ORDER' => 'Die ausgewählte Bestellung ist nicht mit Unzer Payment bezahlt.',
    'UNZER_TOTAL_AMOUNT' => 'Gesamtbetrag',
    'UNZER_CHARGED_AMOUNT' => 'Eingezogener Betrag',
    'UNZER_CANCELLED_AMOUNT' => 'Erstatteter Betrag',
    'UNZER_REMAINING_AMOUNT' => 'Verbleibender Betrag',
    'UNZER_TIME' => 'Zeit',
    'UNZER_TYPE' => 'Typ',
    'UNZER_AMOUNT' => 'Betrag',
    'UNZER_STATUS' => 'Status',
    'UNZER_CONFIRM_ACTION' => 'Soll die Aktion tatsächlich ausgeführt werden?',
    'UNZER_CONFIRM_ACTION_CAPTURE' => 'Soll der folgende Betrag wirklich eingezogen werden: ',
    'UNZER_CONFIRM_ACTION_REFUND' => 'Soll der folgende Betrag wirklich erstattet werden: ',
    'UNZER_CONFIRM_ACTION_CANCEL' => 'Soll die Transaktion wirklich abgebrochen werden: ',
    'UNZER_CAPTURE_AMOUNT' => 'Betrag einziehen',
    'UNZER_REFUND_AMOUNT' => 'Betrag erstatten',
    'UNZER_CANCEL_ORDER' => 'Payment abbrechen',
    'UNZER_LEGACY_ORDER_INFO' => 'ACHTUNG: Die Bestellung wurde mit einem älteren, nicht mehr unterstützten Unzer Modul durchgeführt. Sie können jedoch weiterhin Einzug und Erstattung durchführen!',

    'UNZER_PLEASE_TRANSFER' => 'Bitte überweisen Sie den Betrag in Höhe von %s %s auf das folgende Konto:',
    'UNZER_HOLDER' => 'Kontoinhaber',
    'UNZER_IBAN' => 'IBAN',
    'UNZER_BIC' => 'BIC',
    'UNZER_PLEASE_USE_DESCRIPTOR' => 'Bitte nutzen Sie diese Identifikationsnummer als Verwendungszweck',

];

