<?php

$sLangName = 'English';

$aLang = [
    'charset' => 'UTF-8',

    'SHOP_MODULE_GROUP_unzer_payment_main' => 'Main Settings',
    'SHOP_MODULE_GROUP_unzer_payment_specific' => 'Extended Settings',
    'SHOP_MODULE_UnzerPaymentMode' => 'Mode',
    'SHOP_MODULE_UnzerPaymentMode_0' => 'Sandbox',
    'SHOP_MODULE_UnzerPaymentMode_1' => 'Production',
    'SHOP_MODULE_UnzerPaymentPublicKey' => 'Public Key',
    'SHOP_MODULE_UnzerPaymentPrivateKey' => 'Private Key',
    'SHOP_MODULE_UnzerPaymentLogLevel' => 'Log Level',
    'SHOP_MODULE_UnzerPaymentLogLevel_ERROR' => 'ERROR: Log only errors',
    'SHOP_MODULE_UnzerPaymentLogLevel_WARNING' => 'WARNING: Log warnings and errors',
    'SHOP_MODULE_UnzerPaymentLogLevel_DEBUG' => 'DEBUG: Log all information',
    'SHOP_MODULE_UnzerPaymentClickToPay' => 'Activate Click to Pay for card payments',
    'SHOP_MODULE_UnzerPaymentCardChargeMode' => 'Card booking mode',
    'SHOP_MODULE_UnzerPaymentApplepayChargeMode' => 'Apple Pay booking mode',
    'SHOP_MODULE_UnzerPaymentGooglepayChargeMode' => 'Google Pay booking mode',
    'SHOP_MODULE_UnzerPaymentPaypalChargeMode' => 'Paypal booking mode',
    'SHOP_MODULE_UnzerPaymentWeroChargeMode' => 'Wero booking mode',
    'SHOP_MODULE_UnzerPaymentCardChargeMode_authorize' => 'authorize',
    'SHOP_MODULE_UnzerPaymentCardChargeMode_charge' => 'charge',
    'SHOP_MODULE_UnzerPaymentApplepayChargeMode_authorize' => 'authorize',
    'SHOP_MODULE_UnzerPaymentApplepayChargeMode_charge' => 'charge',
    'SHOP_MODULE_UnzerPaymentGooglepayChargeMode_authorize' => 'authorize',
    'SHOP_MODULE_UnzerPaymentGooglepayChargeMode_charge' => 'charge',
    'SHOP_MODULE_UnzerPaymentPaypalChargeMode_authorize' => 'authorize',
    'SHOP_MODULE_UnzerPaymentPaypalChargeMode_charge' => 'charge',
    'SHOP_MODULE_UnzerPaymentWeroChargeMode_authorize' => 'authorize',
    'SHOP_MODULE_UnzerPaymentWeroChargeMode_charge' => 'charge',
    'UNZER_WEBHOOKS' => 'Webhooks',
    'UNZER_ID' => 'ID',
    'UNZER_SHORT_ID' => 'Short-ID',
    'UNZER_WEBHOOK_EVENT' => 'Event',
    'UNZER_WEBHOOK_URL' => 'URL',
    'UNZER_WEBHOOK_DELETE_CONFIRM' => 'Do you really want to delete this webhook?',
    'UNZER_WEBHOOK_CREATE_CONFIRM' => 'Do you really want to register the webhook?',
    'UNZER_CREATE_WEBHOOK' => 'Register webhook',
    'tbclorder_unzerpayment' => 'Unzer Payment',
    'NO_UNZER_PAYMENT_ORDER' => 'The selected order is not an Unzer Payment order',
    'UNZER_TOTAL_AMOUNT' => 'Total amount',
    'UNZER_CHARGED_AMOUNT' => 'Charged amount',
    'UNZER_CANCELLED_AMOUNT' => 'Cancelled amount',
    'UNZER_REMAINING_AMOUNT' => 'Remaining amount',
    'UNZER_TIME' => 'Time',
    'UNZER_TYPE' => 'Type',
    'UNZER_AMOUNT' => 'Amount',
    'UNZER_STATUS' => 'Status',
    'UNZER_CONFIRM_ACTION' => 'Should the action really be executed?',
    'UNZER_CONFIRM_ACTION_CAPTURE' => 'Are you sure to capture the following amount: ',
    'UNZER_CONFIRM_ACTION_REFUND' => 'Are you sure to refund the following amount: ',
    'UNZER_CONFIRM_ACTION_CANCEL' => 'Are you sure to cancel the following amount: ',
    'UNZER_CAPTURE_AMOUNT' => 'Capture amount',
    'UNZER_REFUND_AMOUNT' => 'Refund amount',
    'UNZER_CANCEL_ORDER' => 'Cancel amount',
    'UNZER_LEGACY_ORDER_INFO' => 'ATTENTION: The order has been placed with a legacy, unsupported module. You still can capture and refund amounts.',

    'UNZER_PLEASE_TRANSFER' => 'Please transfer the amount of %s %s to the following account:',
    'UNZER_HOLDER' => 'Account Holder',
    'UNZER_IBAN' => 'IBAN',
    'UNZER_BIC' => 'BIC',
    'UNZER_PLEASE_USE_DESCRIPTOR' => 'Please use only this identification number as the descriptor',

];

